### ISSUE TITLE
Can't get how to use/install eww and panellauncher.tint2rc missing

### ISSUE THREAD

**Issue by aleemont** [Axarva/dotfiles-2.0#1]
I cloned the `eww` repo on my pc and built it using
 `cargo +nightly build --release`
And then I copied `eww/target/release` in `~/bin`

And then if I run tint2conf `panellauncher.tint2rc` does not exist.
Am I missing something?

**Comment by Axarva** [comment]
Hey there, if you built eww correctly and it didn’t have any issues building, and copied the resulting binary to ~/bin, hitting “Mod4 + S” should launch the sidebar, and hitting “Mod4 + Shift + S” should close it.
Can you verify this? Because I haven’t yet covered the keybinds in the README
As for panellauncher.tint2rc, could you check the contents of your ~/.config/tint2? If it isn’t present there, you can copy it to that location by looking into the tint2 folder of this repo. And are you using an installer? If so, which one? Because I have had 3 people test the Arch installer and the other installer, and it’s worked fine. I’m pretty sure we can figure this out. :)

**Comment by aleemont** [comment]
Will verify it all. Thank you for your answer. I'm going to figure it out and maybe make a pull request for README.md if you'd like so.

**Comment by Axarva** [comment]
Ah, that’d be great! I’ll look forward to it!

**Comment by aleemont** [comment]
Was my bad.
