### ISSUE TITLE
am Dead .......................

### ISSUE THREAD

**Issue by Ayushkun** [Axarva/dotfiles-2.0#142]
first - the logout button didnt ever worked i had to reboot it so many times whis was annoyinh :(
second - i did the tutorial thing but the wheather never worked and profile photo never worked .
third -  i cant play minecraft , my client doesnt launch in xmonad idk why (not the dot files fault)
4th - after upgrading my system eww broke and all eww panels dont work.

**Comment by DivaySaini** [comment]
please share your distro details and did you installed all the dependencies and the fonts?

also, savvynik's tutorial is outdated now.

**Comment by Axarva** [comment]
Possibly Arch, since they mentioned a system update broke eww. I suggest recompiling eww and placing the new binary in your ~/bin. 
The logout button not working is odd, try running the command “killall xmonad” on your terminal and see if it logs you out.

There’s a new tutorial that’s up to date now, and finally, I’m really not sure why minecraft doesn’t work.

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened.
