### ISSUE TITLE
install-on-arch.sh

### ISSUE THREAD

**Issue by Silverfox28** [Axarva/dotfiles-2.0#15]
In my opinion
`(cd ~/.srcs/yay/ && makepkg -si )`

change to
`cd ~/.srcs/yay/ && makepkg -si `

and after
`mkdir -p ~/.config/`
there should be
`cd ~/.dotfiles-2.0`

**Comment by Axarva** [comment]
Could you specify a reason as well? Because the current implementation is shorter, doesn't interfere, and has no side-effects as far as I can see. Either way, thank you for taking the time to actually look into the script!

**Comment by Axarva** [comment]
I did a bit of research on this. Since we don't know the directory in which the user has cloned the repository, `cd ~/.dotfiles-2.0` will basically not work. Not to mention it won't work in case the user decides to clone the directory in another name. `cd -` might work, but the method currently used in the script uses a different shell to carry out the operations. I believe that the implementation in the file currently might be the best way here (shorter, doesn't have uncertainties). 

Of course, this is open for further discussions, but since this isn't strictly an issue, I'll be closing this. Feel free to comment again and I'll make sure to reopen this :)
