### ISSUE TITLE
bad documentation and key bindings

### ISSUE THREAD

**Issue by RajrupDasid** [Axarva/dotfiles-2.0#150]
how can i save screenshots? where is the variable that explains me the exact keybinding to save the screenshots?
what  type of documentation is this?

**Comment by Axarva** [comment]
The screenshot keybinds are explained in the file xmonad.hs in the xmonad/ directory of this repository. Line 131, to be exact. Of course, I believe everyone to be able to look at the variable names “maimcopy” and “maimsave” and understand which keybind saves screenshots and which copies them to their clipboard.
The README clearly explains that keybindings not included can be looked up in xmonad.hs. That is, of course, if you read the README.

Overall, I’d say it’s a pretty comprehensive type of documentation although there might be a few faults here and there, especially since there’s only one person **actively** working on the project. But of course, all documentation becomes useless if you don’t read it.

**Comment by RajrupDasid** [comment]
> The screenshot keybinds are explained in the file xmonad.hs in the xmonad/ directory of this repository. Line 131, to be exact. Of course, I believe everyone to be able to look at the variable names “maimcopy” and “maimsave” and understand which keybind saves screenshots and which copies them to their clipboard. The README clearly explains that keybindings not included can be looked up in xmonad.hs. That is, of course, if you read the README.
> 
> Overall, I’d say it’s a pretty comprehensive type of documentation although there might be a few faults here and there, especially since there’s only one person **actively** working on the project. But of course, all documentation becomes useless if you don’t read it.

I have found the exact key bindings for this without even changing it 
press windows button +function and print screen button together then mouse left click and everything will be done
