### ISSUE TITLE
Widgets dont appear correctly or do not function.

### ISSUE THREAD

**Issue by allusive-dev** [Axarva/dotfiles-2.0#184]
When opening any of the menus, "Sidebar, Dashboard or the powermenu" either the buttons do not do anything or the menu does not display correctly.

![2023-03-13_15-54](https://user-images.githubusercontent.com/99632976/224611373-a3b08ef5-83a1-4d99-a5a6-1e14e991ba09.png)

**To Reproduce**
1. Setup using arch-install script.
2. Open a menu using the shortcuts "Win + P", "Win + S", "Win + Shift + Q"

**Expected behavior**
Buttons should execute related commands and display correctly.

**Desktop**

  OS: Arch Linux x86_64
  Shell: zsh 5.9
  Resolution: 1920x1080, 2560x1440
  WM: xmonad
  Terminal: alacritty
  CPU: 12th Gen Intel i5-12600 (12) @ 6.100GH
  GPU: NVIDIA GeForce RTX 3060
  Memory:  32GB

**Comment by Alllusive** [comment]
I have decided to re-code the widgets myself since I haven't gotten a response here.
Also a ton of the features do not work because they use commands that do not exist on arch Linux such as "amixer" which I re-coded to support "pactl".

**Comment by Axarva** [comment]
`amixer` refers to alsamixer, which should be available if you have the package `alsactl`. `pactl` wasn't used because I didn't want to assume everyone was already using PulseAudio.

As for the widgets not working well, the appearance does need to be re-coded if you're using on a resolution other than the ones in the repo, and would have to check if all the scripts provided are working well. Also ensure that the packages related to the widgets are installed.

**Comment by Axarva** [comment]
Also, the 2560x1440 setup hasn't been personally tested by me, since I simply don't have a screen of that resolution. It was solely made by a generous contributor, so I apologize if there are a lot of bugs.

**Comment by allusive-dev** [comment]
Hello Axarva!
Thank you for getting back to me, I wasn't sure what package created the `amixer` command.
In the meantime I have been slowly fixing the widgets. I never got to fix the widgets in the screenshot as that would have been way too big of a task. But I did restore the sidebar to functionality and the rofi power menu.
