### ISSUE TITLE
Picom feat. Nvidia

### ISSUE THREAD

**Issue by 187Qrly** [Axarva/dotfiles-2.0#19]
Hey bro, 

First, your theme looks great, 
better than everyone others could ever do.
But there's a problem:
I can't really do anything after the installation.
When I, for example want to open the terminal, I need to switch workspaces do get something even displayed.
I am pretty sure that's caused on the compositor.
Maby you could help me.

I am running arch Linux x86_64,
with an RTX 2060 super
AMD ryzen 5 3600x

with kind regards, 

187Qrly :)

**Comment by Axarva** [comment]
I am not so sure about this since I don't use an Nvidia GPU. Maybe disabling the compositor will be a temporary solution, although for a long-term one you'd have to look at forums and fiddle with picom configurations.

[This thread here](https://www.reddit.com/r/archlinux/comments/ermwak/picom_and_nvidia/) might be helpful.

**Comment by 187Qrly** [comment]
yea, ok :( 
All I tried didn't work

**Comment by 187Qrly** [comment]
I will keep on trying, but anyways thanks for replying :) 
Good luck for your future

**Comment by Axarva** [comment]
Thank you!
