### ISSUE TITLE
Sidebar Scaling

### ISSUE THREAD

**Issue by Alooman** [Axarva/dotfiles-2.0#33]
Hey! So I installed this setup by following savvynik's vid. However my end result looks a bit different from the pictures on the github page. when I launch my side bar it ends halfway down my screen, but in the github pics it goes all the way down. is there any way to scale it so that it does so? my laptop resolution is 1920x1080. i tried to do tint2conf but there was no option for the sidebar. pls help. Ok, so I read the github and u said u made this for 1366x768. Could u pls make one for 1920x1080 as my scaling of widgets Is gone for a toss

**Comment by Axarva** [comment]
Does everything else look fine? 

The sidebar issue for 1920x1080 exists. The contributor who imported the configs to 1920x1080 resolution couldn’t fix the sidebar due to their personal reasons, henceforth it appears small. It’s high time I looked into this, but I do not own a device with 1920x1080 resolution, which is causing this problem. I’ll see if I can fix this, but it might take some time.

**Comment by Alooman** [comment]
Everything is fine except the scaling of some widgets (like sidebar) others also look weird but I edit them using tint2conf.

**Comment by Alooman** [comment]
Also, @Axarva could u walk me through the shortcuts please. Im having trouble understanding where my keybinds for volume and brightness are

**Comment by Axarva** [comment]
Closing since a follow-up took place in Discord. Please comment if anything else bothers you!
