### ISSUE TITLE
ZSH doesn't automatically install.

### ISSUE THREAD

**Issue by WILDMARINEMUFFIN** [Axarva/dotfiles-2.0#51]
Using the latest Arch iso,
when using the ./install-on-arch.sh script when the installation is complete and the script explains that there is additional steps to complete, on previous installs the script waited for around 10 ish seconds then asked if you would like to install and switch to zsh as the primary terminal emulator. on my current install it didnt ask to install zsh. zsh was not previously installed on my system before i ran the script and after the script completed my system didnt have zsh on it.

**Comment by Axarva** [comment]
zsh was removed as a hard dependency a few PR merges ago. Unless the script stopped due to an error, that should be fine.

If you’d like to use zsh, you could install it through your package manager and use it. However, you’ll need to include your ~/bin directory in the $PATH of bash (which means in the .bashrc file) mandatorily, and if you use another shell, it’d be better to include it there too.

**Comment by WILDMARINEMUFFIN** [comment]
do you have the old config that use'd to be included in the install as i liked the look it had, thanks.

**Comment by Axarva** [comment]
Clone the repository and issue:

git checkout ea6aa18 


Then execute the install script. This should give you the results you expect.

**Comment by Kellegram** [comment]
> 
> 
> do you have the old config that use'd to be included in the install as i liked the look it had, thanks.

Is there something specific that you mean? There is no difference visually now vs before. The only thing that's changed is that zsh is no longer required and hence not installed. You can get zsh yourself and get oh-my-zsh and set it up the way you like, or just leave it at defaults, which iirc is what this config did.

**Comment by WILDMARINEMUFFIN** [comment]
Didnt realise it was the defaults, my bad. Thanks for the help :).
